######################################################################
# Automatically generated by qmake (3.0) ti tammikuuta 2 18:58:26 2018
######################################################################

TEMPLATE = app
TARGET = combo_box
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
RESOURCES += resource.qrc
